package com.hg.constant;

import java.util.HashMap;
import java.util.Map;

public class ProductChn {
	
	public static Map<String, String> getChnCloumns(){
		Map<String, String> cloumns = new HashMap<String, String>();
		cloumns.put("productNum", "生产编号");
		cloumns.put("code", "代号");
		cloumns.put("poNum", "合同号");
		cloumns.put("poDate", "交货期");
		cloumns.put("poUpdateDate", "更改交货期");
		cloumns.put("remarksA", "备注1");
		cloumns.put("remarksB", "备注2");
		cloumns.put("material", "材质");
		cloumns.put("grade", "等级");
		cloumns.put("serialNum", "锻件编号");
		cloumns.put("orderNum", "序号");
		cloumns.put("sizeA", "规格第1列");
		cloumns.put("sizeB", "规格第2列");
		cloumns.put("sizeC", "规格第3列");
		cloumns.put("sizeD", "规格第4列");
		cloumns.put("sizeE", "规格第5列");
		cloumns.put("sizeF", "规格第6列");
		cloumns.put("sizeG", "规格第7列");
		cloumns.put("sizeH", "规格第8列");
		cloumns.put("poQty", "合同数量");
		cloumns.put("blankWeight", "下料重");
		cloumns.put("qty", "生产数量");
		cloumns.put("description", "说明");
		cloumns.put("qualityRequire", "质量要求");
		cloumns.put("ndtRequire", "探伤要求");
		cloumns.put("deliveryState", "交货状态");
		cloumns.put("htRequire", "热处理要求1");
		cloumns.put("htRequireB", "热处理要求2");
		cloumns.put("hdnsRequire", "硬度要求");
		cloumns.put("nextProcess", "后续工序");
		cloumns.put("otherRequire", "其他要求");
		cloumns.put("forgingEquip", "锻造工艺设备");
		cloumns.put("materialNum", "物料号");
		cloumns.put("dwgNum", "图号");
		cloumns.put("startDate", "下达日期");
		cloumns.put("blankDateA", "下料出坯日期");
		cloumns.put("blankRemarkA", "下料出坯备注");
		cloumns.put("blankInspectDate", "下料检验日期");
		cloumns.put("forgingWorkerA", "锻造出坯加工方");
		cloumns.put("forgingInDateA", "锻造出坯投入日期");
		cloumns.put("forgingOutDateA", "锻造出坯转出日期");
		cloumns.put("heatTreatInDateA", "热处理出坯投入日期");
		cloumns.put("heatTreatOutDateA", "热处理出坯转出日期");
		cloumns.put("blankDate", "下料日期");
		cloumns.put("blankRemark", "下料备注");
		cloumns.put("heatNum", "下料炉号");
		cloumns.put("hlSize", "合料或出坯规格");
		cloumns.put("supplier", "供应商");
		cloumns.put("ignotNum", "锭节号");
		cloumns.put("forgingWorker", "锻造加工方");
		cloumns.put("forgingInDate", "锻造转入");
		cloumns.put("forgingOutDate", "锻造转出");
		cloumns.put("forgingRemark", "锻造备注");
		cloumns.put("afterForgingWorker", "锻后热处理加工方");
		cloumns.put("afterForgingInDate", "锻后热处理转入");
		cloumns.put("atterForgingOutDate", "锻后热处理转出");
		cloumns.put("afterForgingOut", "外协单位");
		cloumns.put("roughMachingWorker", "粗加工加工方");
		cloumns.put("roughMachingInDate", "粗加工转入");
		cloumns.put("roughMachingOutDate", "粗加工转出");
		cloumns.put("roughMachingWeight", "粗加工重量");
		cloumns.put("roughMachingRemark", "粗加工调度备注");
		cloumns.put("roughMachingOutRemark", "粗加工外协备注");
		
		cloumns.put("roughMachingOutCom", "粗加工外协单位");
		cloumns.put("ispsa", "是否喷砂(粗车)");
		cloumns.put("perHeatTreatWorker", "性能热处理加工方");
		cloumns.put("perHeatTreatInDate", "性能热处理转入");
		cloumns.put("perHeatTreatOutDate", "性能热处理转出");
		cloumns.put("sampleInDate", "取样转入");
		cloumns.put("sampleOutDate", "取样转出");
		cloumns.put("deliveryWorker", "交货加工加工方");
		cloumns.put("deliveryInDate", "交货加工转入");
		cloumns.put("deliveryOutDate", "交货加工转出");
		cloumns.put("deliveryOutRemark", "交货加工外协备注");
		cloumns.put("deliveryOutCom", "交货加工外协单位");
		cloumns.put("ispsb", "是否喷砂(交货加工)");
		cloumns.put("deliveryInDate", "交货加工转入");
		cloumns.put("processRemark", "备注");
		cloumns.put("actUnitWeight", "实际重量");
		return cloumns;
	};

}
